import { StyleSheet } from 'react-native';
import { COLORS, SPACING } from '../../../shared/styles';

const styles = StyleSheet.create({
  header: {
    backgroundColor: COLORS.primary,
    padding: SPACING.xl,
    borderRadius: SPACING.md,
    marginBottom: SPACING.xl,
    marginTop: SPACING.md,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.white,
    marginBottom: SPACING.xs,
  },
  headerSubtitle: {
    color: COLORS.blue100,
    fontSize: 16,
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: SPACING.xl,
  },
  gridItem: {
    backgroundColor: COLORS.white,
    width: '48%',
    padding: SPACING.xl,
    borderRadius: SPACING.md,
    alignItems: 'center',
    marginBottom: SPACING.lg,
    borderWidth: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  gridTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.gray800,
    marginTop: SPACING.sm,
    textAlign: 'center',
  },
  gridSubtitle: {
    fontSize: 12,
    color: COLORS.gray500,
    marginTop: SPACING.xs,
    textAlign: 'center',
  },
  arrivalCard: {
    backgroundColor: COLORS.warningLight,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.warning,
    padding: SPACING.lg,
    borderRadius: SPACING.sm,
    marginBottom: SPACING.xl,
  },
  arrivalContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  arrivalText: {
    marginLeft: SPACING.md,
  },
  arrivalTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.warningDark,
  },
  arrivalTime: {
    color: COLORS.warningDark,
    fontSize: 14,
  },
  infoSection: {
    backgroundColor: COLORS.white,
    padding: SPACING.lg,
    borderRadius: SPACING.md,
    marginBottom: SPACING.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.gray800,
    marginBottom: SPACING.md,
  },
  infoItem: {
    fontSize: 14,
    color: COLORS.gray600,
    marginBottom: SPACING.sm,
    lineHeight: 20,
  },
  driverLocationSection: {
    marginBottom: SPACING.xl,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.gray800,
    marginBottom: SPACING.md,
    marginLeft: SPACING.md,
  },
  // Compact Route Selector Styles
  compactRouteSelector: {
    backgroundColor: COLORS.white,
    padding: SPACING.md,
    borderRadius: SPACING.md,
    marginBottom: SPACING.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  compactRouteInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  compactRouteText: {
    flex: 1,
    marginRight: SPACING.md,
  },
  compactRouteName: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.gray800,
    marginBottom: 2,
  },
  compactRouteDetails: {
    fontSize: 12,
    color: COLORS.gray600,
  },
  compactRouteActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  compactRouteFare: {
    fontSize: 14,
    color: COLORS.success,
    fontWeight: '600',
    marginRight: SPACING.sm,
  },
  originalFare: {
    fontSize: 12,
    color: COLORS.gray500,
    textDecorationLine: 'line-through',
    marginTop: -2,
    textAlign: 'right',
  },
  compactRouteButton: {
    backgroundColor: COLORS.primaryLight,
    padding: SPACING.sm,
    borderRadius: SPACING.sm,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: COLORS.white,
    borderTopLeftRadius: SPACING.lg,
    borderTopRightRadius: SPACING.lg,
    maxHeight: '70%',
    paddingTop: SPACING.lg,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
    paddingBottom: SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gray200,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.gray800,
  },
  modalCloseButton: {
    padding: SPACING.sm,
  },
  routesList: {
    paddingHorizontal: SPACING.lg,
    paddingTop: SPACING.md,
  },
  loadingText: {
    textAlign: 'center',
    color: COLORS.gray500,
    fontSize: 16,
    padding: SPACING.xl,
  },
  routeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.white,
    padding: SPACING.lg,
    borderRadius: SPACING.md,
    marginBottom: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.gray200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  selectedRouteItem: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primaryLight,
  },
  routeItemContent: {
    flex: 1,
  },
  routeItemName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.gray800,
    marginBottom: SPACING.xs,
  },
  routeItemDetails: {
    fontSize: 14,
    color: COLORS.gray600,
    marginBottom: SPACING.xs,
  },
  routeItemFare: {
    fontSize: 14,
    color: COLORS.success,
    fontWeight: '500',
  },
  // Empty State Styles
  emptyState: {
    alignItems: 'center',
    padding: SPACING.xl,
  },
  emptyStateText: {
    fontSize: 16,
    color: COLORS.gray500,
    marginBottom: SPACING.lg,
    textAlign: 'center',
  },
  retryButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.md,
    borderRadius: SPACING.sm,
  },
  retryButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '500',
  },
  
  // Active Trip Styles
  activeTripInfo: {
    flex: 1,
  },
  activeTripTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.white,
    marginBottom: SPACING.xs,
  },
  activeTripSubtitle: {
    fontSize: 14,
    color: COLORS.blue100,
  },
  cancelButton: {
    backgroundColor: COLORS.warning,
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mapContainer: {
    height: 300,
    margin: SPACING.lg,
    borderRadius: SPACING.md,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  map: {
    flex: 1,
  },
  tripInfo: {
    backgroundColor: COLORS.white,
    margin: SPACING.lg,
    padding: SPACING.lg,
    borderRadius: SPACING.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  routeInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  routeText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.gray800,
    flex: 1,
  },
  fareText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  statusInfo: {
    marginBottom: SPACING.md,
  },
  statusText: {
    fontSize: 14,
    color: COLORS.gray600,
    marginBottom: SPACING.xs,
  },
  locationText: {
    fontSize: 14,
    color: COLORS.gray600,
  },
  completeButton: {
    backgroundColor: COLORS.success,
    padding: SPACING.md,
    borderRadius: SPACING.sm,
    alignItems: 'center',
  },
  completeButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },

  // Modern Active Trip Styles
  modernActiveTripHeader: {
    backgroundColor: COLORS.white,
    padding: SPACING.lg,
    marginTop: SPACING.md,
    borderRadius: SPACING.md,
    marginHorizontal: SPACING.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  tripStatusIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  statusDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: SPACING.sm,
  },
  tripStatusText: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.gray800,
  },
  tripDriverInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  driverAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: SPACING.md,
  },
  driverDetails: {
    flex: 1,
  },
  driverName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.gray800,
    marginBottom: 2,
  },
  jeepneyNumber: {
    fontSize: 14,
    color: COLORS.gray600,
  },
  modernCancelButton: {
    position: 'absolute',
    top: SPACING.md,
    right: SPACING.md,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.gray100,
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Modern Trip Info Styles
  modernTripInfo: {
    margin: SPACING.lg,
    gap: SPACING.md,
  },
  routeCard: {
    backgroundColor: COLORS.white,
    padding: SPACING.lg,
    borderRadius: SPACING.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  routeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.md,
  },
  routeTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.gray800,
    marginLeft: SPACING.sm,
  },
  routeDetails: {
    gap: SPACING.sm,
  },
  routePoint: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  routeDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: SPACING.md,
  },
  routePointText: {
    fontSize: 14,
    color: COLORS.gray700,
    flex: 1,
  },
  routeLine: {
    width: 2,
    height: 20,
    backgroundColor: COLORS.gray300,
    marginLeft: 5,
  },
  fareCard: {
    backgroundColor: COLORS.white,
    padding: SPACING.lg,
    borderRadius: SPACING.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  fareHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.sm,
  },
  fareTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.gray800,
    marginLeft: SPACING.sm,
  },
  fareAmount: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  driverLocationCard: {
    backgroundColor: COLORS.white,
    padding: SPACING.lg,
    borderRadius: SPACING.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  driverLocationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.sm,
  },
  driverLocationTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.gray800,
    marginLeft: SPACING.sm,
  },
  driverLocationText: {
    fontSize: 14,
    color: COLORS.gray600,
  },
  modernCompleteButton: {
    backgroundColor: COLORS.success,
    padding: SPACING.lg,
    borderRadius: SPACING.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  modernCompleteButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
    marginLeft: SPACING.sm,
  },


  // Tips Section Styles
  tipsSection: {
    backgroundColor: COLORS.primaryLightest,
    margin: SPACING.lg,
    padding: SPACING.md,
    borderRadius: SPACING.sm,
    borderLeftWidth: 4,
    borderLeftColor: COLORS.primary,
  },
  tipsText: {
    fontSize: 14,
    color: COLORS.gray700,
    lineHeight: 20,
    fontStyle: 'italic',
  },

  modernActiveTripContent: {
    margin: SPACING.lg,
    gap: SPACING.md,
  },

  // Trip Completion Loading Overlay Styles
  tripCompletionOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
  tripCompletionContent: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: SPACING.xl,
  },
  tripCompletionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.gray800,
    marginTop: SPACING.lg,
    marginBottom: SPACING.sm,
    textAlign: 'center',
  },
  tripCompletionSubtitle: {
    fontSize: 16,
    color: COLORS.gray600,
    textAlign: 'center',
    lineHeight: 22,
  },

  // Search styles
  searchContainer: {
    marginBottom: SPACING.lg,
    paddingHorizontal: SPACING.lg,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.gray300,
    paddingHorizontal: SPACING.md,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  searchIcon: {
    marginRight: SPACING.sm,
  },
  searchInput: {
    flex: 1,
    paddingVertical: SPACING.md,
    fontSize: 16,
    color: COLORS.gray800,
  },
  clearButton: {
    padding: SPACING.xs,
    marginLeft: SPACING.sm,
  },
  searchResultsText: {
    fontSize: 14,
    color: COLORS.gray600,
    marginTop: SPACING.sm,
    textAlign: 'center',
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: COLORS.gray500,
    marginTop: SPACING.xs,
    textAlign: 'center',
  },
  searchResultsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
    backgroundColor: COLORS.blue50,
    borderTopLeftRadius: SPACING.md,
    borderTopRightRadius: SPACING.md,
  },
  searchResultsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.blue800,
  },
  
  // Debug button styles
  debugSection: {
    marginBottom: SPACING.md,
    alignItems: 'center',
  },
  debugButton: {
    backgroundColor: '#ff4444',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    borderRadius: SPACING.sm,
    gap: SPACING.xs,
  },
  debugButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },

});

export default styles;