// Simple PDF service that creates downloadable content without external dependencies
class SimplePDFService {
  /**
   * Generate a simple text-based report for driver statistics
   */
  static generateDriverStatsReport(driverData, earningsData, dailyEarnings = []) {
    const report = this.createTextReport(driverData, earningsData, dailyEarnings);
    return this.downloadAsText(report, `driver-stats-${driverData?.first_name || 'driver'}-${new Date().toISOString().split('T')[0]}.txt`);
  }

  /**
   * Generate a simple text-based report for daily earnings
   */
  static generateDailyEarningsReport(dailyEarnings, driverData) {
    const report = this.createDailyEarningsTextReport(dailyEarnings, driverData);
    return this.downloadAsText(report, `daily-earnings-${driverData?.first_name || 'driver'}-${new Date().toISOString().split('T')[0]}.txt`);
  }

  /**
   * Create text report for driver statistics
   */
  static createTextReport(driverData, earningsData, dailyEarnings = []) {
    const date = new Date().toLocaleDateString();
    let report = '';
    
    report += '='.repeat(60) + '\n';
    report += 'LAKBAI DRIVER STATISTICS REPORT\n';
    report += `Generated on: ${date}\n`;
    report += '='.repeat(60) + '\n\n';

    // Driver Information
    report += 'DRIVER INFORMATION\n';
    report += '-'.repeat(20) + '\n';
    if (driverData) {
      report += `Name: ${driverData.first_name} ${driverData.last_name}\n`;
      report += `Phone: ${driverData.phone_number}\n`;
      report += `Jeepney: ${driverData.assignedJeepney?.jeepneyNumber || 'Not Assigned'}\n`;
      report += `Status: ${driverData.is_verified ? 'Verified' : 'Pending'}\n`;
    }
    report += '\n';

    // Earnings Summary
    report += 'EARNINGS SUMMARY\n';
    report += '-'.repeat(20) + '\n';
    if (earningsData) {
      report += `Today's Performance:\n`;
      report += `  Earnings: ₱${earningsData.todayEarnings?.toFixed(2) || '0.00'}\n`;
      report += `  Trips: ${earningsData.todayTrips || 0}\n\n`;
      
      report += `Weekly Performance:\n`;
      report += `  Earnings: ₱${earningsData.weeklyEarnings?.toFixed(2) || '0.00'}\n`;
      report += `  Trips: ${earningsData.weeklyTrips || 0}\n\n`;
      
      report += `Monthly Performance:\n`;
      report += `  Earnings: ₱${earningsData.monthlyEarnings?.toFixed(2) || '0.00'}\n`;
      report += `  Trips: ${earningsData.monthlyTrips || 0}\n`;
      report += `  Average Fare: ₱${earningsData.averageFare?.toFixed(2) || '0.00'}\n\n`;
    }

    // Daily Earnings Table
    if (dailyEarnings && dailyEarnings.length > 0) {
      report += 'DAILY EARNINGS BREAKDOWN\n';
      report += '-'.repeat(30) + '\n';
      report += 'Date'.padEnd(12) + 'Earnings'.padEnd(12) + 'Trips'.padEnd(8) + 'Avg Fare\n';
      report += '-'.repeat(50) + '\n';
      
      dailyEarnings.slice(0, 20).forEach(day => {
        report += `${day.date}`.padEnd(12) + 
                 `₱${day.earnings?.toFixed(2) || '0.00'}`.padEnd(12) + 
                 `${day.trips || 0}`.padEnd(8) + 
                 `₱${day.averageFare?.toFixed(2) || '0.00'}\n`;
      });
    }

    report += '\n' + '='.repeat(60) + '\n';
    report += 'Generated by LakbAI Driver Dashboard\n';
    report += '='.repeat(60) + '\n';

    return report;
  }

  /**
   * Create text report for daily earnings
   */
  static createDailyEarningsTextReport(dailyEarnings, driverData) {
    const date = new Date().toLocaleDateString();
    let report = '';
    
    report += '='.repeat(60) + '\n';
    report += 'DAILY EARNINGS REPORT\n';
    report += `Generated on: ${date}\n`;
    report += '='.repeat(60) + '\n\n';

    // Driver Information
    if (driverData) {
      report += `Driver: ${driverData.first_name} ${driverData.last_name}\n`;
      report += `Jeepney: ${driverData.assignedJeepney?.jeepneyNumber || 'Not Assigned'}\n\n`;
    }

    // Daily Earnings Table
    report += 'DAILY EARNINGS BREAKDOWN\n';
    report += '-'.repeat(50) + '\n';
    report += 'Date'.padEnd(12) + 'Earnings'.padEnd(12) + 'Trips'.padEnd(8) + 'Avg Fare\n';
    report += '-'.repeat(50) + '\n';
    
    dailyEarnings.forEach(day => {
      report += `${day.date}`.padEnd(12) + 
               `₱${day.earnings?.toFixed(2) || '0.00'}`.padEnd(12) + 
               `${day.trips || 0}`.padEnd(8) + 
               `₱${day.averageFare?.toFixed(2) || '0.00'}\n`;
    });

    // Summary
    const totalEarnings = dailyEarnings.reduce((sum, day) => sum + (day.earnings || 0), 0);
    const totalTrips = dailyEarnings.reduce((sum, day) => sum + (day.trips || 0), 0);
    const averageDailyEarnings = dailyEarnings.length > 0 ? totalEarnings / dailyEarnings.length : 0;

    report += '\n' + '-'.repeat(50) + '\n';
    report += 'SUMMARY\n';
    report += '-'.repeat(20) + '\n';
    report += `Total Earnings: ₱${totalEarnings.toFixed(2)}\n`;
    report += `Total Trips: ${totalTrips}\n`;
    report += `Average Daily Earnings: ₱${averageDailyEarnings.toFixed(2)}\n`;

    report += '\n' + '='.repeat(60) + '\n';
    report += 'Generated by LakbAI Driver Dashboard\n';
    report += '='.repeat(60) + '\n';

    return report;
  }

  /**
   * Download text content as file
   */
  static downloadAsText(content, filename) {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

export default SimplePDFService;
